#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
xrandr --output Virtual-1 --mode 1920x1200 --scale 1x1 &
VBoxClient --clipboard &
picom &
feh --bg-fill Downloads/fondo1.jpg &
