# Hook: Solely for aesthetic reasons 
set_prompt() {
    if [[ $EUID -eq 0 ]]; then
				PROMPT='%F{#c96b6b}󰈸%f %F{#c0a76b}%~%f %F{#c96b6b}#%f '
    else
			 PROMPT='%F{#8da7c7}󰈸%f %F{#c0a76b}%~%f %F{#9b7fa3}❯%f '
    fi
}

precmd() { set_prompt }

# ctr+l = clear
bindkey -s "^L"  "clear^M"

# ls
alias ll='ls -lh'
alias la='ls -a'
alias l='ls -l'
alias lla='ls -lha '
alias ls='ls '


if [ -f /usr/share/zsh-sudo/sudo.plugin.zsh ]; then
	source /usr/share/zsh-sudo/sudo.plugin.zsh
fi
